spec:
  template:
    spec:
      containers:
        - imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: password
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: url
